# the name of your track or event
name = "Browsers & Platforms"

# the name handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Dietrich Ayala"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 16:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
# priority = 1

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Learn the current status, ongoing challenges, and upcoming work 
  to integrate IPFS and related technologies into browsers and the web itself,
  operating systems and other libraries, toolkits, environments and more.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   16:00 (On 30 Oct, 1h Camp wrapup begins at 16:00)
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:00"
speakers=["@autonome"]
title="Welcome and Introductions"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@lidel"]
title="Gateways of the Future (and Now Too)"
description="New features of the IPFS HTTP gateway, and where it's going: Not only fully trustless, verifiable retrieval (including IPNS!), but also data ingestion, authoring, and support beyond files and directories."

[[timeslots]]
startTime="TBD"
speakers=["@javifernandez"]
title="Chrome pre-defined Custom Handlers for IPFS"
description="""
High-level overview of the refactoring Implemented in Chrome's source code to define a dedicated component for the Custom Handlers logic. 

Thanks to this refactoring, we have improved the support for Chrome embedders to implement their own pre-defined Custom Handlers for the schemes they consider strategic. 

Patching Chrome to add a pre-defined Custom Handler to manage IPFS schemes is now trivial, reducing considerably the efforts of embedders to deal with rebases in order to sync with Chrome upstream.
"""

[[timeslots]]
startTime="TBD"
speakers=["@ikreymer"]
title="Webrecorder"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@rangermauve"]
title="Agregore"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@markg85"]
title="IPFS in All the Things"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@meandavidjustice"]
title="IPFS Browser Extensions"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@onyb"]
title="Brave browser (tbd)"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@fabricedesre"]
title="Capyloon"
description=""

[[timeslots]]
startTime="TBD"
speakers=["@autonome"]
title="Turning the Biggest Ship: IPFS Browser Integrations and the Web Platform"
description=""

[[timeslots]]
# 15 minutes
startTime="TBD"
speakers=["@Jorropo"]
title="UnixFS and IPFS Light Clients"
description=""

#[[timeslots]]
#startTime="11:30"
#speakers=[]
#title="Break"
#description=""
#
#[[timeslots]]
#startTime="13:00"
#speakers=[]
#title="Lunch Break"
#description=""

